=== cyrhla/loader/Tests/fixtures/schema/container-1.0.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema
    elementFormDefault="qualified"
    targetNamespace="http://www.cyrhla.com/2017/schema/container"
    xmlns:con="http://www.cyrhla.com/2017/schema/container"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:annotation>
        <xs:documentation xml:lang="en"><![CDATA[
            XML Schema for http://www.cyrhla.com/2017/schema/container namespace

            Created 2017-03-11

            Created by
            Krystian Pietruszka (kpietru@cyrhla.com)

            Generator with option "Salami Slice"
            http://www.freeformatter.com/xsd-generator.html
            Result modified!
        ]]></xs:documentation>
    </xs:annotation>

    <xs:element name="container">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="con:imports" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="con:parameters" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="con:services" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="imports">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="con:import" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="import">
        <xs:complexType>
            <xs:attribute type="xs:string" name="resource" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="parameters">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="con:parameter" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="parameter">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute type="xs:string" name="id" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="services">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="con:service" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="service">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element ref="con:arguments" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="con:argument" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="con:calls" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="con:call" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="con:tags" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="con:tag" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="id" use="required"/>
            <xs:attribute type="xs:string" name="alias" use="optional"/>
            <xs:attribute type="xs:string" name="class" use="required"/>
            <xs:attribute type="xs:boolean" name="public" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="calls">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="con:call" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="call">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="con:arguments" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="con:argument" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="method" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="arguments">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="con:argument" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="argument" type="xs:string"/>

    <xs:element name="tags">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="con:tag" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="tag" type="xs:string"/>

</xs:schema>

=== cyrhla/loader/Tests/Processor/fixtures/container.xml
<?xml version="1.0" encoding="utf-8"?>
<container
    xmlns="http://www.cyrhla.com/2017/schema/container"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.cyrhla.com/2017/schema/container http://www.cyrhla.com/2017/schema/container-1.0.xsd">

    <parameters>
        <parameter id="foo"></parameter>
        <parameter id="bar">-.10</parameter>
        <parameter id="baz"> 0 </parameter>
        <parameter id="null">false </parameter>
    </parameters>

    <services>

        <service id="bar" alias="żółć" class=" " public="true">
            <arguments>
                <argument>arg1</argument>
                <argument>arg2</argument>
            </arguments>
            <argument>arg3</argument>
            <call method="someMethod">
                <arguments>
                    <argument>a1</argument>
                    <argument>a2</argument>
                </arguments>
                <argument>a3</argument>
            </call>
            <tags>
                <tag>tag1</tag>
                <tag>tag2</tag>
            </tags>
            <tag>tag3</tag>
        </service>

        <service id="baz" class="@some/module/Class" public="false">
            <arguments>
                <argument></argument>
                <argument> </argument>
            </arguments>
            <argument> żółć </argument>
            <call method="someMethod">
                <arguments>
                    <argument>-.10</argument>
                </arguments>
                <argument>undefined</argument>
            </call>
            <tags>
                <tag>tag1</tag>
                <tag>tag2</tag>
            </tags>
            <tag>tag3
</tag>
        </service>

    </services>

</container>

=== cyrhla/loader/Tests/fixtures/container.xml
<?xml version="1.0" encoding="utf-8"?>
<container
    xmlns="http://www.cyrhla.com/2017/schema/container"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.cyrhla.com/2017/schema/container http://www.cyrhla.com/2017/schema/container-1.0.xsd">

    <imports>
        <import resource="translator.xml"/>
    </imports>

    <parameters>
        <parameter id="foo"></parameter>
        <parameter id="bar">-.10</parameter>
        <parameter id="baz"> 0 </parameter>
        <parameter id="null">false </parameter>
        <parameter id=" {}"> []</parameter>
        <parameter id="{}">[]</parameter>
        <parameter id="[0,false]">{
            "foo": null,
            "bar": "baz"
        }</parameter>
    </parameters>

    <services>

        <service id="bar" alias="żółć" class=" " public="true">
            <arguments>
                <argument>arg1</argument>
                <argument>arg2</argument>
            </arguments>
            <argument>arg3</argument>
            <call method="someMethod">
                <arguments>
                    <argument>a1</argument>
                    <argument>a2</argument>
                </arguments>
                <argument>a3</argument>
            </call>
            <tags>
                <tag>tag1</tag>
                <tag>tag2</tag>
            </tags>
            <tag>tag3</tag>
        </service>

        <service id="baz" class="@some/module/Class" public="false">
            <arguments>
                <argument></argument>
                <argument> </argument>
            </arguments>
            <argument> żółć </argument>
            <calls>
                <call method="someMethod">
                    <arguments>
                        <argument> 9
</argument>
                        <argument>999999999999999</argument>
                        <argument>9999999999999999</argument>
                        <argument>9.999999999999999</argument>
                        <argument>999999999999999999999</argument>
                    </arguments>
                    <argument>undefined</argument>
                </call>
            </calls>
            <tags>
                <tag>tag1</tag>
                <tag>tag2</tag>
            </tags>
            <tag>tag3
</tag>
        </service>

    </services>

</container>
