=== cyrhla/loader/Tests/fixtures/schema/translator-1.0.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema
    elementFormDefault="qualified"
    targetNamespace="http://www.cyrhla.com/2017/schema/translator"
    xmlns:tran="http://www.cyrhla.com/2017/schema/translator"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:annotation>
        <xs:documentation xml:lang="en"><![CDATA[
            XML Schema for http://www.cyrhla.com/2017/schema/translator namespace

            Created 2017-03-11

            Created by
            Krystian Pietruszka (kpietru@cyrhla.com)

            Generator with option "Salami Slice"
            http://www.freeformatter.com/xsd-generator.html
            Result modified!
        ]]></xs:documentation>
    </xs:annotation>

    <xs:element name="translator">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tran:imports" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="tran:translations" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="imports">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tran:import" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="import">
        <xs:complexType>
            <xs:attribute type="xs:string" name="resource" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="translations">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tran:translation" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="translation">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tran:text" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="id" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="text">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute type="xs:string" name="lang" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== cyrhla/loader/Tests/fixtures/translator.xml
<?xml version="1.0" encoding="utf-8"?>
<translator
    xmlns="http://www.cyrhla.com/2017/schema/translator"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.cyrhla.com/2017/schema/translator http://www.cyrhla.com/2017/schema/translator-1.0.xsd">

    <imports>
        <import resource="data3.json"/>
        <import resource="data3.json"/>
    </imports>

    <translations>

        <translation id="blog.HELLO">
            <text lang="en">Hello</text>
            <text lang="de">Halo</text>
            <text lang="fr">Bnjour</text>
            <text lang="pl">Cześć</text>
        </translation>

        <translation id="blog.GREEN">
            <text lang="en">green</text>
            <text lang="de">grün</text>
            <text lang="fr">vert</text>
            <text lang="pl">zielony</text>
        </translation>

    </translations>

</translator>
